### ISSUE TITLE
Clarify what this project is and what it can do

### ISSUE THREAD

**Issue by Ashark** [alex1701c/jetbrains-api#2]
The readme is not verbose at the moment. Could you please clarify it. This project is an "unofficial way" of parsing pycharm configs, right?

Can this be used for changing project config on the fly? Please see https://gitlab.com/AndrewShark/pycharm-scripts/-/issues/1. I wonder if I can improve my project with using this jetbrains-api. Could it be possible to change the Script path field in run/debug configuration in before launch tools?

**Comment by alex1701c** [comment]
The project is intended for reading the recently used project from the Jetbrains IDEs. I had kept the name vague, because I was thinking about adding further functionality, though at this point in time I do not have a usecase.

I only created this as a dedicated repo, because I did not want to duplicate the code in my KRunner and Dolphin plugins.

**Comment by alex1701c** [comment]
Please reopen if you have further questions or my response/the readme was not clear.
